/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurant;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JTextField;

import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author ADMIN
 */
public class OO_Restaurant extends javax.swing.JFrame {

    /**
     * Creates new form OO_Restaurant
     */
    public OO_Restaurant() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jtxtTax = new javax.swing.JTextField();
        jtxtTotal = new javax.swing.JTextField();
        jtxtSubTotal = new javax.swing.JTextField();
        jlblSubTotal = new javax.swing.JLabel();
        jlblTax = new javax.swing.JLabel();
        jlblTotal = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jlblTax4 = new javax.swing.JLabel();
        jlblTax5 = new javax.swing.JLabel();
        jlblTax6 = new javax.swing.JLabel();
        jtxtTotalCost = new javax.swing.JTextField();
        jtxtCostDrink = new javax.swing.JTextField();
        jtxtCostMeal = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jlblTotal2 = new javax.swing.JLabel();
        jtxtBaconandCheese = new javax.swing.JTextField();
        jtxtChickenBurgerM = new javax.swing.JTextField();
        jtxtChickenBurger = new javax.swing.JTextField();
        jlblSubTotal2 = new javax.swing.JLabel();
        jlblTax2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlblTax3 = new javax.swing.JLabel();
        jtxtFillet_O_Fish = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jbtn_total = new javax.swing.JButton();
        jbtn_receipt = new javax.swing.JButton();
        jbtn_reset = new javax.swing.JButton();
        jbtn_exit = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtReceipt = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jlblTotal1 = new javax.swing.JLabel();
        jtxtVanMilkShake = new javax.swing.JTextField();
        jtxtChocMilkShake = new javax.swing.JTextField();
        jtxtMilkShake = new javax.swing.JTextField();
        jlblSubTotal1 = new javax.swing.JLabel();
        jlblTax1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlblTotal3 = new javax.swing.JLabel();
        jtxtClasVanilla = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 66)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Restaurant Management System");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 8));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel1)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(23, 23, 23))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 1350, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jtxtTax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jtxtTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jtxtSubTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jlblSubTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblSubTotal.setText("SubTotal");

        jlblTax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTax.setText("Tax");

        jlblTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTotal.setText("Total");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblSubTotal)
                    .addComponent(jlblTotal)
                    .addComponent(jlblTax))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(jtxtSubTotal, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtTax, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(23, 23, 23))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTax))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblSubTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTotal)
                    .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 470, 430, 160));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jlblTax4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTax4.setText("Cost of Meal");

        jlblTax5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTax5.setText("Total Cost of Made");

        jlblTax6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTax6.setText("Cost of Drinks");

        jtxtTotalCost.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jtxtCostDrink.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jtxtCostMeal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jlblTax4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addComponent(jtxtCostMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblTax6)
                            .addComponent(jlblTax5))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtCostDrink)
                            .addComponent(jtxtTotalCost))))
                .addGap(29, 29, 29))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jtxtCostMeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtCostDrink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jlblTax4)
                        .addGap(18, 18, 18)
                        .addComponent(jlblTax6)
                        .addGap(18, 18, 18)
                        .addComponent(jlblTax5)))
                .addGap(22, 22, 22))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 460, 160));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jlblTotal2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTotal2.setText("Bacon and Cheese Burger");

        jtxtBaconandCheese.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtBaconandCheese.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtBaconandCheese.setText("0");
        jtxtBaconandCheese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBaconandCheeseActionPerformed(evt);
            }
        });

        jtxtChickenBurgerM.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtChickenBurgerM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtChickenBurgerM.setText("0");

        jtxtChickenBurger.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtChickenBurger.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtChickenBurger.setText("0");

        jlblSubTotal2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblSubTotal2.setText("Chicken Burger Meal");

        jlblTax2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTax2.setText("Fillet-O-Fish");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Meals");

        jlblTax3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTax3.setText("Chicken Burger");

        jtxtFillet_O_Fish.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtFillet_O_Fish.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtFillet_O_Fish.setText("0");
        jtxtFillet_O_Fish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFillet_O_FishActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblSubTotal2)
                            .addComponent(jlblTotal2)
                            .addComponent(jlblTax2)
                            .addComponent(jlblTax3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtxtBaconandCheese, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtChickenBurgerM, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtChickenBurger)
                            .addComponent(jtxtFillet_O_Fish, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel3)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtChickenBurger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTax3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblSubTotal2)
                    .addComponent(jtxtChickenBurgerM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblTotal2)
                    .addComponent(jtxtBaconandCheese, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTax2)
                    .addComponent(jtxtFillet_O_Fish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 460, 270));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jbtn_total.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtn_total.setText("TOTAL");
        jbtn_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_totalActionPerformed(evt);
            }
        });

        jbtn_receipt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtn_receipt.setText("Receipt");
        jbtn_receipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_receiptActionPerformed(evt);
            }
        });

        jbtn_reset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtn_reset.setText("Reset");
        jbtn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_resetActionPerformed(evt);
            }
        });

        jbtn_exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtn_exit.setText("Exit");
        jbtn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jbtn_total, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jbtn_receipt, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(jbtn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jbtn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtn_exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_receipt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_total, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 900, 80));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jtxtReceipt.setColumns(20);
        jtxtReceipt.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jtxtReceipt.setRows(5);
        jScrollPane1.setViewportView(jtxtReceipt);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 190, 430, 540));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jlblTotal1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTotal1.setText("Chocolate Milk Shake");

        jtxtVanMilkShake.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtVanMilkShake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtVanMilkShake.setText("0");

        jtxtChocMilkShake.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtChocMilkShake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtChocMilkShake.setText("0");

        jtxtMilkShake.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtMilkShake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtMilkShake.setText("0");

        jlblSubTotal1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblSubTotal1.setText("Vanilla Milk Shake");

        jlblTax1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTax1.setText("Milk Shake ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Drinks");

        jlblTotal3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTotal3.setText("Classic Vanilla");

        jtxtClasVanilla.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtClasVanilla.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtClasVanilla.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblTotal1)
                    .addComponent(jlblSubTotal1)
                    .addComponent(jlblTax1)
                    .addComponent(jlblTotal3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtxtClasVanilla, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                        .addGap(53, 53, 53))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtxtVanMilkShake, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtMilkShake, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .addComponent(jtxtChocMilkShake))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtMilkShake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTax1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlblSubTotal1)
                        .addGap(18, 18, 18)
                        .addComponent(jlblTotal1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlblTotal3)
                        .addGap(43, 43, 43))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtxtVanMilkShake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtChocMilkShake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtClasVanilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 430, 270));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtBaconandCheeseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBaconandCheeseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtBaconandCheeseActionPerformed

    private void jtxtFillet_O_FishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFillet_O_FishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFillet_O_FishActionPerformed

    private void jbtn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_exitActionPerformed
        SubClass_Child iExit = new SubClass_Child(); //Inheritance
        iExit.iExitSystem();
    }//GEN-LAST:event_jbtn_exitActionPerformed

    private void jbtn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_resetActionPerformed
        JTextField cleartext = null;
        
        for (Component c:jPanel1.getComponents()){
            if (c.getClass().toString().contains("javax.swing.JTextField")){
                cleartext = (JTextField)c;
                cleartext.setText("0");
            }
        }
            //==========================================================
        
        for (Component c:jPanel5.getComponents()){
            if (c.getClass().toString().contains("javax.swing.JTextField")){
                cleartext = (JTextField)c;
                cleartext.setText("0");
            }
        }
        //==============================================================
        for (Component c:jPanel4.getComponents()){
            if (c.getClass().toString().contains("javax.swing.JTextField")){
                cleartext = (JTextField)c;
                cleartext.setText("");
            }
        }
            //==========================================================
        
        for (Component c:jPanel3.getComponents()){
            if (c.getClass().toString().contains("javax.swing.JTextField")){
                cleartext = (JTextField)c;
                cleartext.setText("");
            }
        }
        //==============================================================
        jtxtReceipt.setText(null);
    }//GEN-LAST:event_jbtn_resetActionPerformed

    private void jbtn_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_totalActionPerformed
        // TODO add your handling code here:
        SubClass_Child ItemCost = new SubClass_Child();
        
        double iTax , iSubTotal, iTotal;
        
        ItemCost.ChickenBurger = ItemCost.pChickenBurger * Double.parseDouble
        (jtxtChickenBurger.getText());
        ItemCost.ChickenBurgerM = ItemCost.pChickenBurgerM * Double.parseDouble
        (jtxtChickenBurgerM.getText());
        ItemCost.BaconCheeseBurger = ItemCost.pBaconCheeseBurger * Double.parseDouble
        (jtxtBaconandCheese.getText());
        ItemCost.Filet_O_Fish = ItemCost.pFilet_O_Fish * Double.parseDouble
        (jtxtFillet_O_Fish.getText());
        
        ItemCost.MilkShake = ItemCost.pMilkShake * Double.parseDouble
        (jtxtMilkShake.getText());
        ItemCost.VanMilkShake = ItemCost.pVanMilkShake * Double.parseDouble
        (jtxtVanMilkShake.getText());
        ItemCost.ChocMilkShake = ItemCost.pChocMilkShake * Double.parseDouble
        (jtxtChocMilkShake.getText());
        ItemCost.ClasVanilla = ItemCost.pClasVanilla * Double.parseDouble
        (jtxtClasVanilla.getText());
        
        iSubTotal = ItemCost.GetAmount();
        iTax = ItemCost.cFindTax(iSubTotal);
        iTotal = iSubTotal + iTax;
        
        String SubTotal = String.format("Rp. %.2f", iSubTotal);
        jtxtSubTotal.setText(SubTotal);
        jtxtCostMeal.setText(SubTotal);
        
        String Tax = String.format("Rp. %.2f", iTax);
        jtxtTax.setText(Tax);
        jtxtCostDrink.setText(Tax);
        
        String Total = String.format("Rp. %.2f", iTotal);
        jtxtTotal.setText(Total);
        jtxtTotalCost.setText(Total);
        
        String Meal = String.format("Rp. %.2f", ItemCost.Meals);
        jtxtCostMeal.setText(Meal);
        
        String Drink = String.format("Rp. %.2f", ItemCost.Drinks);
        jtxtCostDrink.setText(Drink);
        
        String TotalCost = String.format("Rp. %.2f", ItemCost.TotalofMD);
        jtxtTotalCost.setText(TotalCost);
    }//GEN-LAST:event_jbtn_totalActionPerformed

    private void jbtn_receiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_receiptActionPerformed
        
        //==========================================================
        int refs = 1325 + (int)(Math.random()*4238);
        
        //=========================================================
        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
        tTime.format(timer.getTime());
        
                   
                    jtxtReceipt.append("\tRestaurant Management Systems:\n"+
                            "Reference:\t\t\t" + refs + 
                    "\n========================================\n" +
                            "Meals:\t\t" + jtxtCostMeal.getText()+"\n\n" +
                            "Drinks:\t\t" + jtxtCostDrink.getText()+"\n\n" +
                            "Cost of Items:\t" + jtxtTotalCost.getText()+"\n\n"+
                    "===========================================" + "\n\n" + 
                    "Tax:\t\t" + jtxtTax.getText()+ "\n\n" + 
                            "Subtotal:\t" + jtxtSubTotal.getText()+ "\n\n" +
                            "Total:\t\t" + jtxtTotal.getText()+ "\n"+
                            
                "====================================" +
                            "\n\n\t\tThank you");
                    
                     
            
    }//GEN-LAST:event_jbtn_receiptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, IllegalAccessException, InstantiationException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OO_Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OO_Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OO_Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OO_Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OO_Restaurant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtn_exit;
    private javax.swing.JButton jbtn_receipt;
    private javax.swing.JButton jbtn_reset;
    private javax.swing.JButton jbtn_total;
    private javax.swing.JLabel jlblSubTotal;
    private javax.swing.JLabel jlblSubTotal1;
    private javax.swing.JLabel jlblSubTotal2;
    private javax.swing.JLabel jlblTax;
    private javax.swing.JLabel jlblTax1;
    private javax.swing.JLabel jlblTax2;
    private javax.swing.JLabel jlblTax3;
    private javax.swing.JLabel jlblTax4;
    private javax.swing.JLabel jlblTax5;
    private javax.swing.JLabel jlblTax6;
    private javax.swing.JLabel jlblTotal;
    private javax.swing.JLabel jlblTotal1;
    private javax.swing.JLabel jlblTotal2;
    private javax.swing.JLabel jlblTotal3;
    private javax.swing.JTextField jtxtBaconandCheese;
    private javax.swing.JTextField jtxtChickenBurger;
    private javax.swing.JTextField jtxtChickenBurgerM;
    private javax.swing.JTextField jtxtChocMilkShake;
    private javax.swing.JTextField jtxtClasVanilla;
    private javax.swing.JTextField jtxtCostDrink;
    private javax.swing.JTextField jtxtCostMeal;
    private javax.swing.JTextField jtxtFillet_O_Fish;
    private javax.swing.JTextField jtxtMilkShake;
    private javax.swing.JTextArea jtxtReceipt;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    private javax.swing.JTextField jtxtTotalCost;
    private javax.swing.JTextField jtxtVanMilkShake;
    // End of variables declaration//GEN-END:variables
}
